ALTER TABLE "User" ADD COLUMN "lastLoginAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "passwordUpdatedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "memberSince" DATETIME;
ALTER TABLE "User" ADD COLUMN "dateOfBirth" DATETIME;
ALTER TABLE "User" ADD COLUMN "rank" TEXT;
ALTER TABLE "User" ADD COLUMN "pk" TEXT;
ALTER TABLE "User" ADD COLUMN "hasPossessionCard" INTEGER NOT NULL DEFAULT 0;
